#**S02 T04**#

In [1]:
import numpy as np
import pandas as pd

##*Exercice 1*##

*Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.*

In [21]:
one_dimension_array = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

def statistic_summary():
    if one_dimension_array.ndim != 1:
        print("Error, the array is multidimensional.")
    df_describe = pd.DataFrame(one_dimension_array)
    return df_describe.describe()

statistic_summary()

0
count  10.000000
mean   11.000000
std     6.055301
min     2.000000
25%     6.500000
50%    11.000000
75%    15.500000
max    20.000000

##*Exercice 2*##

*Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.*

In [22]:
def create_matrix():
    return np.random.randint(0, 100, (6, 6))
    
create_matrix()

array([[91, 54,  2,  9, 59, 47],
       [12, 92, 56, 87, 10, 42],
       [84, 63, 48, 60, 78, 67],
       [91,  9,  3,  8, 32, 35],
       [84, 73, 83, 82, 98, 62],
       [50, 86, 72, 97, 49,  0]])

##*Exercice 3*##

*Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.*

First attempt:

In [54]:
two_dimension_array = [    
                        [2, 4, 6],  
                        [1, 3, 5],  
                        [8, 2, 4]  
                        ];  
def sum_rows_cols():
    rows = len(two_dimension_array);  
    cols = len(two_dimension_array[0]); 

    for i in range(0, rows):  
        sumRow = 0  
        for j in range(0, cols):  
            sumRow = sumRow + two_dimension_array[i][j];  
        print("The sum of " + str(i+1) +" row is " + str(sumRow));  
    
    for i in range(0, rows):  
        sumCol = 0  
        for j in range(0, cols):  
            sumCol = sumCol + two_dimension_array[j][i];  
        print("The sum of " + str(i+1) +" column is " + str(sumCol));
        
sum_rows_cols()

The sum of 1 row is 12
The sum of 2 row is 9
The sum of 3 row is 14
The sum of 1 column is 11
The sum of 2 column is 9
The sum of 3 column is 15


Second attempt:

In [45]:
two_dimension_array2 = np.array([[2, 4, 6],[1, 3, 5],[8, 2, 4]]); 

def sum_rows():
    return np.sum(two_dimension_array2, axis=1)

def sum_cols():
    return np.sum(two_dimension_array2, axis=0)

print(sum_rows())
print(sum_cols())

[12  9 14]
[11  9 15]


##*Exercice 4*##

*Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.*

Primer calculem la covariancia, que és el valor que reflexa en quina quantitat dues variables varien de forma conjunta respecte a les seves mitjanes.

In [32]:
x = np.random.randint(0,20,(2,6))
print(x)

x_mean = x[0].mean() # first row
print(x_mean)

y_mean = x[1].mean() # second row
print(y_mean)

items = len(x[1])
print(items)

mult_row_col = np.prod(x, axis=0)
print(mult_row_col)
row_col = np.sum(mult_row_col)
print(row_col)
cov = (row_col/items) - (x_mean * y_mean)
print(cov)

[[16  3  6 10 13  7]
 [ 4 14 11  0 19 18]]
9.166666666666666
11.0
6
[ 64  42  66   0 247 126]
545
-10.0


Després, calculem les desviacions estàndard, mesura que s'utiliza per a quantificar la variació o la dispersió d'un conjunt de dades numèriques.

In [40]:
square_x = np.square(x)
print(square_x)

sum_square_x_row = np.sum(square_x, axis = 1)
print(sum_square_x_row)

std_1 = np.sqrt((sum_square_x_row[0] / items) - np.square(x_mean))
print(std_1)
std_2 = np.sqrt((sum_square_x_row[1] / items) - np.square(y_mean))
print(std_2)

[[256   9  36 100 169  49]
 [ 16 196 121   0 361 324]]
[ 619 1018]
4.37480158280223
6.976149845485449


Finalment, calculem el coeficient de correlació lineal, que és la covariància entre les multiplicacions de les desviacions estàndard.

In [41]:
corr_coef = cov / (std_1 * std_2)
print(corr_coef)

-0.32766181975830455


Com que el coeficient és més proper a 0 que a 1, és una correlació dèbil. A més, com és negatiu, la correlació és inversa.

Ara, comprovem amb la funció predefinida de numpy si el resultat és correcte.

In [43]:
r = np.corrcoef(x[0],x[1])
print(r)

[[ 1.         -0.32766182]
 [-0.32766182  1.        ]]
